name: app_alert_dialog
description: "A simple customizable alert dialog with two buttons for Flutter apps."
version: 0.0.1
homepage: https://github.com/pankaj1101/app_alert_dialog
repository: https://github.com/pankaj1101/app_alert_dialog

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/success.svg
    - assets/icons/error.svg
